### ISSUE TITLE
Auto-Replant Appears to Occasionally Fail

### ISSUE THREAD

**Issue by thehale** [toomanybugs1/Quick-Farm#2]
As I started to use this plugin today I thought it was broken because my crops didn't seem to automatically replant. Upon closer inspection I realized that this behavior was simply the result of the seed being replanted while my mouse was still clicked and in the hit box of the replanted seed (meaning the seed was immediately rebroken). If I carefully broke the top of the crop, the seed would auto plant just fine since it's hit box was below the point of my cursor from when I broke the ripe crop.

Looking at the code, I think this could be resolved by removing the restriction to only auto-replant fully grown crops. That way, if the replanted seed is accidentally broken in the same click that broke the original crop, it will simply be replanted again (and again if necessary) until the mouse click has ended.

**Comment by toomanybugs1** [comment]
I like this idea! I'll go ahead and make that change soon.

**Comment by toomanybugs1** [comment]
Just fixed this. The new package is pending on the project page. I literally couldn't figure out this problem and it was so simple, thank you!
